### ISSUE TITLE
Potential issues with memory on Android Studio emulator

### ISSUE THREAD

**Issue by chankrista** [MPCS-51039/Session-5#3]
I have gotten to the part of the Android tutorials where we add properties to MainActivity. When I run the app in the emulator, the app consistently opens and closes immediately. This has been difficult for me to troubleshoot because Android Studio does not give me any error message and just says "Gradle build finished..." and "Install successful...". I noticed while watching the task manager that running the emulator can sometimes take up 90+%, sometimes 100% of my CPU and RAM. Is there any way to get around this without needing a new comupter?

**Comment by skoop12** [comment]
@chankrista I cloned your repo and the app is crashing because the tapMeButton in your activity_main.xml file is named "TapMeButton" but in your code you declare and try to access it as tapMeButton, so the app tries to instantiate a null view and crashes. Changing the name to tapMeButton in activity_main.xml resolved the crashing problem for me.

**Comment by chankrista** [comment]
Ooh thank you! @skoop12
